# Generated by Django 3.0.5 on 2020-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='meta_description_uk',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='meta_keywords_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='meta_keywords_uk',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Content for description meta tag, maximum are 200 characters', max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Content for description meta tag, maximum are 200 characters', max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='meta_description_uk',
            field=models.TextField(blank=True, help_text='Content for description meta tag, maximum are 200 characters', max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Content for description meta tag, maximum are 200 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Content for description meta tag, maximum are 200 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_description_uk',
            field=models.TextField(blank=True, help_text='Content for description meta tag, maximum are 200 characters', max_length=255, null=True),
        ),
    ]
