version: '3.7'
services:
 web:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   command: gunicorn portfolio.wsgi -b 0.0.0.0:8000
   volumes:
     - .:/Portfolio
   ports:
     - 8888:8000
   env_file:
     - ./env/django.env
   depends_on:
     - postgres
     - redis

 postgres:
   restart: always
   image: postgres:latest
   env_file:
     - ./env/postgresql.env
   volumes:
     - postgres_data:/var/lib/postgresql/data/

 redis:
   restart: always
   image: redis:latest
   ports:
     - 6379:6379
   volumes:
     - redisdata:/data

volumes:
  postgres_data:
  redisdata:
