version: '3.7'
services:
 web:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   command: gunicorn portfolio.wsgi -b 0.0.0.0:8000
   ports:
     - 8888:8000
   env_file:
     - ./env/django-production.env
   depends_on:
     - postgres
     - redis

 postgres:
   restart: always
   image: postgres:latest
   env_file:
     - ./env/postgresql.env

 redis:
   restart: always
   image: redis:latest
   ports:
     - 6379:6379
